name: Bricoleur
permalink: /posts/:title
pygments: true
markdown: redcarpet
redcarpet:
  extensions: [
    "no_intra_emphasis", 
    "fenced_code_blocks", 
    "autolink", 
    "strikethrough", 
    "superscript", 
    "with_toc_data",
    "lax_spacing",
    "lax_html_blocks",
    "tables"
  ]
